--LANGUAGE plpgsql;
DROP TRIGGER publication_model_check ON fees;
DROP FUNCTION publication_model_check;
DROP TYPE maybe_logic cascade ;
DROP TYPE publication_model cascade;
DROP TYPE fee_category cascade;
DROP TABLE journals cascade;
DROP TABLE publishers cascade;
DROP TABLE owners cascade;
DROP TABLE categories cascade;
DROP TABLE fees cascade;
DROP TABLE institutional_agreements cascade;
DROP TABLE institutions cascade;
DROP TABLE currencies;
DROP TABLE journal_categories;
DROP TABLE publisher_owners;
