title = "Not For Profit"
description = "Help the economy transition to a purpose-driven system"
base_url = "https://notforprofit.netlify.com"

compile_sass = true
highlight_code = false
build_search_index = false

taxonomies = [
    {name = "category", rss = false},
    {name = "tags", rss = false},
]

[extra.author]
name = "Tim DuBois"
