title = "Not For Profit"
description = "Help the economy transition to purpose-driven system"
base_url = "https://notforprofit.netlify.com"

compile_sass = true
highlight_code = false
build_search_index = true

taxonomies = [
    {name = "categories", rss = true},
    {name = "tags", rss = true},
]

[extra.author]
name = "Tim DuBois"
