--LANGUAGE plpgsql;
DROP TRIGGER agreement_url_check ON institutional_agreements;
DROP FUNCTION agreement_url_check;
DROP TYPE maybe_logic cascade ;
DROP TYPE publication_model cascade;
DROP TYPE fee_category cascade;
DROP TABLE journals cascade;
DROP TABLE publishers cascade;
DROP TABLE owners cascade;
DROP TABLE categories cascade;
DROP TABLE fees cascade;
DROP TABLE institutional_agreements cascade;
DROP TABLE institutions cascade;
DROP TABLE currencies;
DROP TABLE journal_categories;
DROP TABLE publisher_owners;
DROP TABLE journal_owners;
DROP TABLE publication_models;
